### ISSUE TITLE
Insert Row Before

### ISSUE THREAD

**Issue by efitzpa1** [tsu-complete/taylorfit#11]
The "Insert Row Before" functionality breaks only after pressing the plus sign to add a row to the bottom. Once the plus sign is pressed, "Insert Row Before" starts to "queue" the rows, and will not push them to the DOM until the plus sign is pressed again. "Insert Row After" works after the plus sign is pressed, however it begins doing the same "queueing" behavior if the plus sign has been pressed followed by the "Insert Row Before" function.

**Comment by tsu-complete** [comment]
Wont fix - stake holder does not want row/col addition
